# config.py
WEBSERVER_URL = "http://localhost:8785/"
DEFAULT_REFRESH_RATE_SECONDS = 2
MAX_HISTORY_POINTS = 30

VARIABLES = [
    # Core
    "CORE_TEMP", "CORE_TEMP_OPERATIVE", "CORE_TEMP_MAX", "CORE_TEMP_MIN", "CORE_TEMP_RESIDUAL",
    "CORE_PRESSURE", "CORE_PRESSURE_MAX", "CORE_PRESSURE_OPERATIVE", "CORE_INTEGRITY", "CORE_WEAR",
    "CORE_STATE", "CORE_STATE_CRITICALITY", "CORE_CRITICAL_MASS_REACHED", "CORE_CRITICAL_MASS_REACHED_COUNTER",
    "CORE_IMMINENT_FUSION", "CORE_READY_FOR_START", "CORE_STEAM_PRESENT", "CORE_HIGH_STEAM_PRESENT",
    # Time
    "TIME", "TIME_STAMP",
    # Coolant Core
    "COOLANT_CORE_STATE", "COOLANT_CORE_PRESSURE", "COOLANT_CORE_MAX_PRESSURE", "COOLANT_CORE_VESSEL_TEMPERATURE",
    "COOLANT_CORE_QUANTITY_IN_VESSEL", "COOLANT_CORE_PRIMARY_LOOP_LEVEL", "COOLANT_CORE_FLOW_SPEED",
    "COOLANT_CORE_FLOW_ORDERED_SPEED", "COOLANT_CORE_FLOW_REACHED_SPEED",
    "COOLANT_CORE_QUANTITY_CIRCULATION_PUMPS_PRESENT", "COOLANT_CORE_QUANTITY_FREIGHT_PUMPS_PRESENT",
    # Coolant Core Pumps (0-2)
    "COOLANT_CORE_CIRCULATION_PUMP_0_STATUS", "COOLANT_CORE_CIRCULATION_PUMP_1_STATUS",
    # ... and so on for all variables
    # ... include the rest of the VARIABLES list ...
    "STEAM_TURBINE_0_PRESSURE", "STEAM_TURBINE_1_PRESSURE", "STEAM_TURBINE_2_PRESSURE",
]
